from GameMapClass import GameMap
from BotClass import Bot
from MapCLass import Map


def change_ship_coordinates(ships, x, y):
    for ship in ships:
        ship['x'] += x
        ship['y'] += y


visualisation = GameMap('https://datsblack.datsteam.dev/json/map/6586ae233e7ba8.12192069.json')
ally_ships = [{'cannonCooldown': 3,
               'cannonCooldownLeft': 0,
               'cannonRadius': 20,
               'cannonShootSuccessCount': 0,
               'direction': 'north',
               'hp': 4,
               'id': 2752,
               'maxChangeSpeed': 5,
               'maxHp': 4,
               'maxSpeed': 10,
               'minSpeed': -1,
               'scanRadius': 60,
               'size': 4,
               'speed': 0,
               'x': 1428,
               'y': 1336}, {'cannonCooldown': 3,
                            'cannonCooldownLeft': 0,
                            'cannonRadius': 20,
                            'cannonShootSuccessCount': 0,
                            'direction': 'north',
                            'hp': 2,
                            'id': 2759,
                            'maxChangeSpeed': 5,
                            'maxHp': 2,
                            'maxSpeed': 10,
                            'minSpeed': -1,
                            'scanRadius': 60,
                            'size': 2,
                            'speed': 0,
                            'x': 1449,
                            'y': 1336}, {'cannonCooldown': 3,
                                         'cannonCooldownLeft': 0,
                                         'cannonRadius': 20,
                                         'cannonShootSuccessCount': 0,
                                         'direction': 'north',
                                         'hp': 2,
                                         'id': 2757,
                                         'maxChangeSpeed': 5,
                                         'maxHp': 2,
                                         'maxSpeed': 10,
                                         'minSpeed': -1,
                                         'scanRadius': 60,
                                         'size': 2,
                                         'speed': 0,
                                         'x': 1443,
                                         'y': 1336}, {'cannonCooldown': 3,
                                                      'cannonCooldownLeft': 0,
                                                      'cannonRadius': 20,
                                                      'cannonShootSuccessCount': 0,
                                                      'direction': 'north',
                                                      'hp': 3,
                                                      'id': 2758,
                                                      'maxChangeSpeed': 5,
                                                      'maxHp': 3,
                                                      'maxSpeed': 10,
                                                      'minSpeed': -1,
                                                      'scanRadius': 60,
                                                      'size': 3,
                                                      'speed': 0,
                                                      'x': 1446,
                                                      'y': 1336}, {'cannonCooldown': 3,
                                                                   'cannonCooldownLeft': 0,
                                                                   'cannonRadius': 20,
                                                                   'cannonShootSuccessCount': 0,
                                                                   'direction': 'north',
                                                                   'hp': 2,
                                                                   'id': 2760,
                                                                   'maxChangeSpeed': 5,
                                                                   'maxHp': 2,
                                                                   'maxSpeed': 10,
                                                                   'minSpeed': -1,
                                                                   'scanRadius': 60,
                                                                   'size': 2,
                                                                   'speed': 0,
                                                                   'x': 1452,
                                                                   'y': 1335}, {'cannonCooldown': 3,
                                                                                'cannonCooldownLeft': 0,
                                                                                'cannonRadius': 20,
                                                                                'cannonShootSuccessCount': 0,
                                                                                'direction': 'north',
                                                                                'hp': 5,
                                                                                'id': 2753,
                                                                                'maxChangeSpeed': 5,
                                                                                'maxHp': 5,
                                                                                'maxSpeed': 10,
                                                                                'minSpeed': -1,
                                                                                'scanRadius': 60,
                                                                                'size': 5,
                                                                                'speed': 0,
                                                                                'x': 1431,
                                                                                'y': 1336}, {'cannonCooldown': 3,
                                                                                             'cannonCooldownLeft': 0,
                                                                                             'cannonRadius': 20,
                                                                                             'cannonShootSuccessCount': 0,
                                                                                             'direction': 'north',
                                                                                             'hp': 3,
                                                                                             'id': 2754,
                                                                                             'maxChangeSpeed': 5,
                                                                                             'maxHp': 3,
                                                                                             'maxSpeed': 10,
                                                                                             'minSpeed': -1,
                                                                                             'scanRadius': 60,
                                                                                             'size': 3,
                                                                                             'speed': 0,
                                                                                             'x': 1434,
                                                                                             'y': 1336},
              {'cannonCooldown': 3,
               'cannonCooldownLeft': 0,
               'cannonRadius': 20,
               'cannonShootSuccessCount': 0,
               'direction': 'north',
               'hp': 4,
               'id': 2755,
               'maxChangeSpeed': 5,
               'maxHp': 4,
               'maxSpeed': 10,
               'minSpeed': -1,
               'scanRadius': 60,
               'size': 4,
               'speed': 0,
               'x': 1437,
               'y': 1337}, {'cannonCooldown': 3,
                            'cannonCooldownLeft': 0,
                            'cannonRadius': 20,
                            'cannonShootSuccessCount': 0,
                            'direction': 'north',
                            'hp': 2,
                            'id': 2751,
                            'maxChangeSpeed': 5,
                            'maxHp': 2,
                            'maxSpeed': 10,
                            'minSpeed': -1,
                            'scanRadius': 60,
                            'size': 2,
                            'speed': 0,
                            'x': 1425,
                            'y': 1336}, {'cannonCooldown': 3,
                                         'cannonCooldownLeft': 0,
                                         'cannonRadius': 20,
                                         'cannonShootSuccessCount': 0,
                                         'direction': 'north',
                                         'hp': 3,
                                         'id': 2756,
                                         'maxChangeSpeed': 5,
                                         'maxHp': 3,
                                         'maxSpeed': 10,
                                         'minSpeed': -1,
                                         'scanRadius': 60,
                                         'size': 3,
                                         'speed': 0,
                                         'x': 1440,
                                         'y': 1335}]
enemy_ships = [{'cannonCooldown': 3,
                'cannonCooldownLeft': 0,
                'cannonRadius': 20,
                'cannonShootSuccessCount': 0,
                'direction': 'north',
                'hp': 4,
                'id': 2752,
                'maxChangeSpeed': 5,
                'maxHp': 4,
                'maxSpeed': 10,
                'minSpeed': -1,
                'scanRadius': 60,
                'size': 4,
                'speed': 0,
                'x': 1428,
                'y': 1346}, {'cannonCooldown': 3,
                             'cannonCooldownLeft': 0,
                             'cannonRadius': 20,
                             'cannonShootSuccessCount': 0,
                             'direction': 'north',
                             'hp': 2,
                             'id': 2759,
                             'maxChangeSpeed': 5,
                             'maxHp': 2,
                             'maxSpeed': 10,
                             'minSpeed': -1,
                             'scanRadius': 60,
                             'size': 2,
                             'speed': 0,
                             'x': 1449,
                             'y': 1346}, {'cannonCooldown': 3,
                                          'cannonCooldownLeft': 0,
                                          'cannonRadius': 20,
                                          'cannonShootSuccessCount': 0,
                                          'direction': 'north',
                                          'hp': 2,
                                          'id': 2757,
                                          'maxChangeSpeed': 5,
                                          'maxHp': 2,
                                          'maxSpeed': 10,
                                          'minSpeed': -1,
                                          'scanRadius': 60,
                                          'size': 2,
                                          'speed': 0,
                                          'x': 1443,
                                          'y': 1346}, {'cannonCooldown': 3,
                                                       'cannonCooldownLeft': 0,
                                                       'cannonRadius': 20,
                                                       'cannonShootSuccessCount': 0,
                                                       'direction': 'north',
                                                       'hp': 3,
                                                       'id': 2758,
                                                       'maxChangeSpeed': 5,
                                                       'maxHp': 3,
                                                       'maxSpeed': 10,
                                                       'minSpeed': -1,
                                                       'scanRadius': 60,
                                                       'size': 3,
                                                       'speed': 0,
                                                       'x': 1446,
                                                       'y': 1346}, {'cannonCooldown': 3,
                                                                    'cannonCooldownLeft': 0,
                                                                    'cannonRadius': 20,
                                                                    'cannonShootSuccessCount': 0,
                                                                    'direction': 'north',
                                                                    'hp': 2,
                                                                    'id': 2760,
                                                                    'maxChangeSpeed': 5,
                                                                    'maxHp': 2,
                                                                    'maxSpeed': 10,
                                                                    'minSpeed': -1,
                                                                    'scanRadius': 60,
                                                                    'size': 2,
                                                                    'speed': 0,
                                                                    'x': 1452,
                                                                    'y': 1345}, {'cannonCooldown': 3,
                                                                                 'cannonCooldownLeft': 0,
                                                                                 'cannonRadius': 20,
                                                                                 'cannonShootSuccessCount': 0,
                                                                                 'direction': 'north',
                                                                                 'hp': 5,
                                                                                 'id': 2753,
                                                                                 'maxChangeSpeed': 5,
                                                                                 'maxHp': 5,
                                                                                 'maxSpeed': 10,
                                                                                 'minSpeed': -1,
                                                                                 'scanRadius': 60,
                                                                                 'size': 5,
                                                                                 'speed': 0,
                                                                                 'x': 1431,
                                                                                 'y': 1346}, {'cannonCooldown': 3,
                                                                                              'cannonCooldownLeft': 0,
                                                                                              'cannonRadius': 20,
                                                                                              'cannonShootSuccessCount': 0,
                                                                                              'direction': 'north',
                                                                                              'hp': 3,
                                                                                              'id': 2754,
                                                                                              'maxChangeSpeed': 5,
                                                                                              'maxHp': 3,
                                                                                              'maxSpeed': 10,
                                                                                              'minSpeed': -1,
                                                                                              'scanRadius': 60,
                                                                                              'size': 3,
                                                                                              'speed': 0,
                                                                                              'x': 1434,
                                                                                              'y': 1346},
               {'cannonCooldown': 3,
                'cannonCooldownLeft': 0,
                'cannonRadius': 20,
                'cannonShootSuccessCount': 0,
                'direction': 'north',
                'hp': 4,
                'id': 2755,
                'maxChangeSpeed': 5,
                'maxHp': 4,
                'maxSpeed': 10,
                'minSpeed': -1,
                'scanRadius': 60,
                'size': 4,
                'speed': 0,
                'x': 1437,
                'y': 1347}, {'cannonCooldown': 3,
                             'cannonCooldownLeft': 0,
                             'cannonRadius': 20,
                             'cannonShootSuccessCount': 0,
                             'direction': 'north',
                             'hp': 2,
                             'id': 2751,
                             'maxChangeSpeed': 5,
                             'maxHp': 2,
                             'maxSpeed': 10,
                             'minSpeed': -1,
                             'scanRadius': 60,
                             'size': 2,
                             'speed': 0,
                             'x': 1425,
                             'y': 1346}, {'cannonCooldown': 3,
                                          'cannonCooldownLeft': 0,
                                          'cannonRadius': 20,
                                          'cannonShootSuccessCount': 0,
                                          'direction': 'north',
                                          'hp': 3,
                                          'id': 2756,
                                          'maxChangeSpeed': 5,
                                          'maxHp': 3,
                                          'maxSpeed': 10,
                                          'minSpeed': -1,
                                          'scanRadius': 60,
                                          'size': 3,
                                          'speed': 0,
                                          'x': 1440,
                                          'y': 1345}]

change_ship_coordinates(ally_ships, -1000, -1000)
change_ship_coordinates(enemy_ships, -1000, -1000)
visualisation.set_ships(ally_ships)
visualisation.set_enemy_ships(enemy_ships)
visualisation.run()


